services:
  seq:
    container_name: seqDS
    image: datalust/seq:latest
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
    ports:
      - "5341:5341"
      - "8081:80"

  postgres:
    container_name: postgresDS
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "DirectoryService"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  redis:
    image: redis:latest
    container_name: redisDS
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres-data:
  redis_data: